import LayoutComponent from '../layout';
import './globals.css';
import * as React from 'react';
import AppProviders from '@/providers/AppProviders';

export const metadata = {
  title: 'Social Pro',
  description: 'Generated by quangnv1911',
};
const RootLayout = ({
                      children,
                    }: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html
      lang="en"
      style={{ colorScheme: 'light' }}
      className="light"
    >
    <body>
    <AppProviders>
      <LayoutComponent>{children}</LayoutComponent>
    </AppProviders>

    </body>
    </html>
  );
};

export default RootLayout;