// Jenkinsfile của social-pro-be

pipeline {
    agent any

    tools {
        maven 'mvn-3.9.9'
        jdk 'jdk 21'
    }

    environment {
        SCANNER_HOME= tool 'sonar-scanner'
    }
    parameters {
        string(name: 'TARGET_BRANCH')
        string(name: 'TAG')
    }
    
    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                git branch: params.TARGET_BRANCH,credentialsId: 'github-credentials', url: 'https://github.com/quangnv1911/SocialPro.git'
             
                
            }
        }
        stage('Clean install') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Sonarqube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    dir('social-pro-be') {
                        sh "$SCANNER_HOME/bin/sonar-scanner"
                    }
                }
            }
        }

         stage('Docker Push Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        dir('social-pro-be') {
                            sh "docker build -t quangnv1911/social-pro-be:${TAG} ."
                            sh "docker push quangnv1911/social-pro-be:${TAG}"
                            sh "docker rmi quangnv1911/social-pro-be:${TAG}"
                        }
                    }
                }
            }
        }
    }
}