// Jenkinsfile của social pro be
pipeline {
  agent any
  stages {
    stage('Check Changes') {
    //   when { changeset "social-pro-be/**" }
      steps {
        script {
          echo "Building social pro be..."
        }
      }
    }
  }
  post {
    success {
      sh 'echo "Build social pro be successful!"'
    }
    failure {
        sh 'echo "Build social pro be failed!"'
    }
  }
}