// Jenkinsfile của social-pro-admin

pipeline {
    agent any
    environment {
        // DOCKER_BUILDKIT='1'
        SCANNER_HOME= tool 'sonar-scanner'
    }
    parameters {
        string(name: 'BRANCH_NAME')
        string(name: 'TAG')
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: params.BRANCH_NAME,credentialsId: 'github-credentials', url: 'https://github.com/quangnv1911/SocialPro.git'
             
                
            }
        }
        stage('Install Dependencies') {
          steps {
            nodejs(nodeJSInstallationName: 'node22') {
            dir('social-pro-admin') {
                sh 'npm install'
            }
            }
          }
        }
        stage('Sonarqube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    dir('social-pro-admin') {
                        sh "$SCANNER_HOME/bin/sonar-scanner"
                    }
                }
            }
        }

         stage('Docker Push Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        dir('social-pro-admin') {
                            sh "docker build -t quangnv1911/social-pro-admin:${params.TAG} ."
                            sh "docker push quangnv1911/social-pro-admin:${params.TAG}"
                            sh "docker rmi quangnv1911/social-pro-admin:${params.TAG}"
                        }
                    }
                }
            }
        }
    }
}