export const LOGIN_PATH = '/login' as '/';
export const HOME_PATH = '/home';
export const USER_PATH = '/users';
export const TODO_PATH = '/todo';
export const CRONJOB_PATH = '/cron-job';
export const SOCIAL_BUFF_PATH = '/social-buff';
export const PAYMENT_PATH = '/payment';
export const MMO_RESOURCE_PATH = '/mmo-resource';
export const PRODUCT_PATH = '/product';