version: '3'
volumes:
  redis-data:
    driver: local
services:
  app:
    image: quangnv1911/payment-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/config.yml:/app/config/config.yml
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - captcha-resolver
    environment:
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CAPTCHA_API_BASE_URL=http://captcha-resolver:1234
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mynetwork

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    networks:
      - mynetwork
  captcha-resolver:
    image: registry.gitlab.com/nhayhoc/bank-captcha-server
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge