spring:
  application:
    name: back-end
  datasource:
    url: jdbc:mysql://localhost:3306/SocialPro
    username: root
    password: 123456
    hikari:
      pool-name: SpringBootBoilerplateHikariPool
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  jta:
    enabled: false

springdoc:
  swagger-ui:
    enabled: true
#
#logging:
#  level:
#    org.springframework: INFO
#    com.farukgenc.boilerplate.springboot: INFO
#
#jwt:
#  secretKey: secret
#  issuer: www.farukgenc.com
#  expirationMinute: 10
#
