name: SonarQube Analysis

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "dev"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
permissions:
  contents: read
  actions: read
  id-token: write


jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      project_dirs: '["./social-pro-client", "./social-pro-admin", "./email-proxy"]'
  sonar:
    uses: ./.github/workflows/sonar.yml
    with:
      project_dirs: '["./social-pro-client", "./social-pro-admin", "./email-proxy", "./social-pro-be"]'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
        project_dirs: "./social-pro-client,./social-pro-admin,./email-proxy"
        spring_project_dirs: "./social-pro-be"
