name: SonarQube Analysis

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      project_dirs: "./social-pro-client,./social-pro-admin,./email-proxy"

  sonar:
    uses: ./.github/workflows/sonar.yml
    with:
      project_dirs: "./social-pro-client,./social-pro-admin,./social-pro-be,./email-proxy"
    
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
        project_dirs: "./social-pro-client,./social-pro-admin,./email-proxy"
        spring_project_dirs: "./social-pro-be"
