name: Sonar Test Workflow

on:
  workflow_call:
    inputs:
        project_dirs:
            required: true
            type: string  
            
jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-dir: ${{ fromJson(inputs.project_dirs) }}  # Chuyển chuỗi thành array

    steps:
      - name: Debug Secrets
        run: |
          if [ -z "$SONAR_TOKEN" ]; then
            echo "❌ SONAR_TOKEN chưa được thiết lập hoặc không tồn tại!"
            exit 1  # Dừng workflow nếu SONAR_TOKEN không tồn tại
          else
            echo "✅ SONAR_TOKEN đã được thiết lập!"
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ matrix.project-dir }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

