name: Sonar Test Workflow

on:
  workflow_call:
    inputs:
        project_dirs:
            required: true
            type: string  
    secrets:
        SONAR_TOKEN:
            required: true
            
jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-dir: ${{ fromJson(inputs.project_dirs) }}  # Chuyển chuỗi thành array

    steps:
      - name: Debug Secrets
        run: |
          if [ -z "$SONAR_TOKEN" ]; then
          echo "SONAR_TOKEN is not set"
          exit 1
          else
          echo "SONAR_TOKEN is set"
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ matrix.project-dir }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

